"""Parsers for the cell grammars the exporters write.

Every one of these columns has a shape, and comparing the shapes beats comparing
the strings. `int a; int b` against `int b; int a` is a reordering of two
parameters, not a changed cell, and only a parser can say so.

The grammars, as `engine/docx_exporter.py` writes them:

    Data Type      "int a; int b"  +  a second paragraph  "return: int"
    Data Range     "0-0xFF; NA"    +  a second paragraph  "return: 0-0xFF"
    Source/Dest    "Layer1.App/Main, Layer1.Cross/Hub"   or  "-"
    Test Steps     one paragraph per step, each "N) ..."
"""
from __future__ import annotations

import re

from .model import is_placeholder

_RETURN_RE = re.compile(r"^return\s*:\s*(.*)$", re.IGNORECASE)
# "1)", "2.a)", "3.b.1.c)" -- SWE.4 test steps nest, alternating numeric and
# alphabetic levels, so the label carries the shape of the control flow.
_STEP_RE = re.compile(r"^\s*\(?([0-9]+(?:\.[0-9a-zA-Z]+)*)\s*[).\]]\s*(.*)$", re.DOTALL)


def typed_list(texts):
    """A Data Type / Data Range cell -> (the per-parameter values, the return value).

    The return line is a paragraph of its own (`return: int`). A cell with no
    return line gives `None`, which is how a global variable row is told apart
    from a function row that returns void.
    """
    params, ret = [], None
    for raw in texts or []:
        line = (raw or "").strip()
        if not line:
            continue
        m = _RETURN_RE.match(line)
        if m:
            ret = m.group(1).strip()
            continue
        for part in line.split(";"):
            part = part.strip()
            if part:
                params.append(part)
    # "VOID" as the whole parameter list means "takes nothing", not a parameter
    if len(params) == 1 and params[0].casefold() == "void":
        params = []
    return params, ret


def name_set(text):
    """A comma-separated cell -> a sorted list of distinct entries, `-` -> []."""
    if is_placeholder(text):
        return []
    parts = [p.strip() for p in re.split(r"[,\n]", str(text)) if p.strip()]
    return sorted({p for p in parts if not is_placeholder(p)})


def numbered(texts):
    """Numbered paragraphs -> [{label, path, body}], in order.

    The label is kept apart from the body because the two say different things.
    A body says what the step does; the label says where the step sits in the
    control flow -- `3.b.1.c` is inside a switch inside an if inside a loop. A
    document that keeps every body and flattens the nesting has changed its
    meaning, and only the labels show it.
    """
    out = []
    for raw in texts or []:
        line = (raw or "").strip()
        if not line:
            continue
        m = _STEP_RE.match(line)
        if m:
            label = m.group(1)
            out.append({"label": label, "path": tuple(label.split(".")),
                        "body": m.group(2).strip()})
        else:
            out.append({"label": "", "path": (), "body": line})
    return out


def steps(texts):
    """Numbered paragraphs -> the step bodies, in order, numbering stripped.

    The numbering is regenerated by whoever writes the document, so comparing it
    would report a renumbering as five changed steps. The bodies are the content.
    """
    return [s["body"] for s in numbered(texts)]


def shape(texts):
    """The nesting of a numbered list, as depth-per-entry -- the tree, no wording."""
    return [len(s["path"]) for s in numbered(texts) if s["path"]]


def bullets(texts, drop_header=None):
    """Paragraphs of a Requirements cell -> its bullets, minus a leading header."""
    out = []
    for raw in texts or []:
        line = re.sub(r"^[•\-\*]\s*", "", (raw or "").strip())
        if not line:
            continue
        if drop_header and line.casefold() == drop_header.casefold():
            continue
        out.append(line)
    return out


def key_value_rows(rows):
    """A two-column vertical table -> {first column: the rest of the row}.

    Used for the Requirements/Risk/Capacity block and for the SWE.4 test-case
    metadata table, which are both written as label-then-value rows.
    """
    out = {}
    for row in rows or []:
        if len(row) < 2:
            continue
        label = row[0].text.strip()
        if not label:
            continue
        out[label] = row[1]
    return out


# A C++ name as a heading prints it: `apply`, `AddOperation::apply`, `operator+`.
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_~][A-Za-z0-9_]*(?:::[A-Za-z_~][A-Za-z0-9_]*)*$")


def function_of(heading, unit_name=""):
    """`Dispatch-AddOperation::apply` -> `AddOperation::apply`.

    The heading is `<Unit>-<Function>`, so the obvious reading is to strip the
    unit's name. That breaks the moment the two documents disagree about the
    unit's name: every function under a renamed unit then looks renamed too, and
    one finding becomes forty.

    So the unit name is only a hint. What actually decides the split is the first
    `-` whose remainder reads as a C++ name -- which also handles a unit whose own
    name has a hyphen in it (`Sample-Core-doThing` -> `doThing`), because
    `Core-doThing` is not a name.
    """
    text = (heading or "").strip()
    if unit_name and text.startswith(unit_name + "-"):
        candidate = text[len(unit_name) + 1:]
        if _IDENTIFIER_RE.match(candidate):
            return candidate
    start = 0
    while True:
        cut = text.find("-", start)
        if cut < 0:
            return text
        candidate = text[cut + 1:]
        if _IDENTIFIER_RE.match(candidate):
            return candidate
        start = cut + 1


def resolve_columns(header, spec):
    """Map a field name to its column index by reading the header row.

    Column *position* is not an identity either: the client's table may carry the
    same eight columns in another order, or name them differently. `spec` is
    {field: [accepted header spellings]}; the first spelling is ours.

    Exact matches are taken first across every field, then prefix matches, so
    `Interface Type` cannot be claimed by `Data Type`'s looser `type` spelling.
    Returns {field: index} for what was found -- a missing field is a finding for
    the comparator, not an error here.
    """
    def probe(s):
        return re.sub(r"[^a-z0-9]+", "", (s or "").casefold())

    probes = [probe(h) for h in header]
    taken, found = set(), {}

    for exact_pass in (True, False):
        for fieldname, spellings in spec.items():
            if fieldname in found:
                continue
            for spelling in spellings:
                want = probe(spelling)
                if not want:
                    continue
                for i, got in enumerate(probes):
                    if i in taken or not got:
                        continue
                    hit = (got == want) if exact_pass else (got.startswith(want) or want.startswith(got))
                    if hit:
                        found[fieldname] = i
                        taken.add(i)
                        break
                if fieldname in found:
                    break
    return found


def find_label(mapping, *candidates):
    """The first cell whose label matches one of `candidates`, ignoring case and
    punctuation -- `Capacity` and `Capacity(Density)` are the same row."""
    def probe(s):
        return re.sub(r"[^a-z0-9]+", "", (s or "").casefold())

    wanted = [probe(c) for c in candidates]
    for label, cell in mapping.items():
        p = probe(label)
        if p in wanted:
            return cell
    for label, cell in mapping.items():
        p = probe(label)
        if any(p.startswith(w) or w.startswith(p) for w in wanted if w):
            return cell
    return None
