"""initial schema - full model (docs/production-redesign/07 section 4)

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-23

Fresh start (D-5): the first migration creates the entire schema from the shared
metadata. Because we begin with an empty database and one source of truth, this
baseline builds from `schema.metadata` rather than duplicating 29 hand-written
`create_table` calls that could silently drift from it. Subsequent migrations are
ordinary autogenerated diffs against the same metadata.
"""
from alembic import op

from api.db.postgres.schema import metadata

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    metadata.create_all(op.get_bind())


def downgrade() -> None:
    metadata.drop_all(op.get_bind())
