"""Can this project detect a code change at all?

Every failure here means an edit can land in the source and reach the document as the
previous version's flowchart, with the run reporting success.
"""
import hashlib

import pytest

pytestmark = pytest.mark.live

# hash_tokens([]) -- the constant every entity libclang could not tokenise collapsed onto.
EMPTY_HASH = hashlib.sha256(b"").hexdigest()


def _sample(keys, n=8):
    return "\n      ".join(sorted(keys)[:n])


class TestHashesExist:
    def test_the_version_has_functions_at_all(self, functions, vid):
        assert functions(vid), (
            "version %s has no function rows. Phase 1 stored nothing, or the model was "
            "cleared by a later flush that was handed no functions." % vid)

    def test_every_real_function_has_a_source_hash(self, real_functions, bare_functions, vid):
        real = real_functions(vid)
        if not real:
            pytest.skip("version %s has no functions with a payload" % vid)
        missing = [k for k, f in real.items() if not f["hash"]]
        assert not missing, (
            "%s: %d of %d functions with a payload have NO source_hash.\n"
            "persist_functions takes source_hash from the `hashes` artifact, so an absent "
            "hash means `hashes` was empty or differently keyed when the model was "
            "persisted. Change detection is dead for the NEXT run even though this run's "
            "document is fine. (%d hash-only rows, which legitimately have no payload.)\n"
            "      %s"
            % (vid, len(missing), len(real), len(bare_functions(vid)), _sample(missing)))

    def test_every_hash_only_row_has_a_hash(self, bare_functions, vid):
        bare = bare_functions(vid)
        if not bare:
            pytest.skip("version %s has no hash-only rows" % vid)
        empty = [k for k, f in bare.items() if not f["hash"]]
        assert not empty, (
            "%s: %d row(s) carry neither a payload nor a hash, so they serve no purpose.\n"
            "      %s" % (vid, len(empty), _sample(empty)))


class TestHashesCanMove:
    def test_no_function_carries_the_empty_token_hash(self, functions, vid):
        fns = functions(vid)
        if not fns:
            pytest.skip("no functions")
        empty = [k for k, f in fns.items() if f["hash"] == EMPTY_HASH]
        pct = 100.0 * len(empty) / len(fns)
        assert not empty, (
            "%s: %d of %d functions (%.0f%%) hash to sha256(\"\").\n"
            "hash_cursor produced that when libclang returned no tokens -- a declaration "
            "made by a macro expansion is the common trigger. Every entity holding it is "
            "UNCHANGED in every comparison forever, so its flowchart and description can "
            "never be regenerated by an edit. Fixed in incremental/hashing.py; a version "
            "parsed before that fix still carries it and must be regenerated rather than "
            "used as a baseline.\n      %s"
            % (vid, len(empty), len(fns), pct, _sample(empty)))

    def test_no_large_cluster_shares_one_hash(self, functions, vid):
        import collections
        fns = functions(vid)
        if not fns:
            pytest.skip("no functions")
        counts = collections.Counter(f["hash"] for f in fns.values() if f["hash"])
        big = [(h, n) for h, n in counts.items() if n > 20 and h != EMPTY_HASH]
        assert not big, (
            "%s: %d hash value(s) are shared by more than 20 functions.\n"
            "Identical bodies hash identically, which is expected for trivial getters and "
            "not for twenty of them. A large cluster usually means the hash is being "
            "computed over something other than the function's own source.\n      %s"
            % (vid, len(big),
               "\n      ".join("%d functions share %s" % (n, h[:12])
                               for h, n in sorted(big, key=lambda x: -x[1])[:5])))


class TestPhaseOneHashesSurvived:
    """Phase 1 snapshots its own hashes.json and nothing afterwards rewrites it.

    That makes the snapshot the authoritative record of what the parse produced, and the
    comparison decides WHERE a hash was lost -- which picks the fix. Missing from the rows
    but present in the snapshot: a later flush destroyed it. Missing from both: the parse
    never made it.
    """

    def _snapshot(self, db, vid):
        from core import model_store
        with db.engine().connect() as cx:
            return model_store.load_parse_snapshot_file(cx, vid, "hashes.json") or {}

    def test_every_hash_phase_one_made_is_still_stored(self, db, functions, vid):
        snap = self._snapshot(db, vid)
        if not snap:
            pytest.skip("version %s has no hashes.json in parse_snapshots" % vid)
        want = {k for k in snap if k.count("|") >= 3}
        have = {k for k, f in functions(vid).items() if f["hash"]}
        lost = want - have
        assert not lost, (
            "%s: %d of %d hashes Phase 1 produced are NOT in the stored rows "
            "(%d rows carry one).\n"
            "The parse made them and the rows do not have them, so a LATER flush dropped "
            "them: persist_model rewrites the version after clear_version, and anything "
            "the flush was not handed is deleted.\n      %s"
            % (vid, len(lost), len(want), len(have), _sample(lost)))

    def test_no_stored_hash_that_phase_one_never_made(self, db, functions, vid):
        snap = self._snapshot(db, vid)
        if not snap:
            pytest.skip("version %s has no hashes.json in parse_snapshots" % vid)
        want = {k for k in snap if k.count("|") >= 3}
        have = {k for k, f in functions(vid).items() if f["hash"]}
        extra = have - want
        assert not extra, (
            "%s: %d stored hash(es) this version's parse never produced.\n"
            "A hash the parse did not make came from somewhere else -- most likely a "
            "PREVIOUS run's stored model being carried into this version's persist, which "
            "is what happens when several run plans write one version id.\n      %s"
            % (vid, len(extra), _sample(extra)))
