"""End-of-run generation report (M3.4).

A human-readable summary of what a generation did — inputs (baseline/scope/commit),
change classification, and reuse accounting (regenerated vs reused per entity kind)
— so it's easy to see how incremental reuse is performing. `build_report` is pure
(takes a stats dict) so it's unit-testable; `emit_report` logs it + saves report.txt.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List

_W = 64
_RULE = "=" * _W
_THIN = "-" * _W


def _pct(part: int, whole: int) -> str:
    return f"{(100 * part // whole) if whole else 0}%"


def _line(label: str, value: Any) -> str:
    return f"  {label:<16}: {value}"


def build_report(stats: Dict[str, Any]) -> List[str]:
    """Build the report lines from a stats dict (see generate_incremental/full)."""
    decision = stats.get("decision", "full")
    L: List[str] = [_RULE, f"  GENERATION REPORT  -  version {stats.get('versionId')}  ({decision})", _RULE]

    L.append(_line("Project", stats.get("projectId")))
    L.append(_line("Branch / commit", f"{stats.get('branch')} / {str(stats.get('commit'))[:10]}"))
    L.append(_line("Scope", stats.get("scope")))
    if decision == "incremental":
        L.append(_line("Baseline", f"{stats.get('baselineVersionId')} @ "
                                   f"{str(stats.get('baselineCommit'))[:10]}  "
                                   f"({stats.get('changedFiles')} changed file(s) in the diff)"))
    else:
        L.append(_line("Baseline", "(none - full generation; becomes the baseline for future runs)"))
    L.append(_line("Data dict", stats.get("dataDictId")))
    L.append(_line("LLM model", stats.get("llmModel")))
    L.append(_line("Status", stats.get("status")))
    if stats.get("elapsedSeconds") is not None:
        L.append(_line("Wall clock", f"{stats['elapsedSeconds']:.1f}s"))

    if decision == "incremental":
        cls = stats.get("classification") or {}
        L.append(_THIN)
        L.append("  CHANGE CLASSIFICATION (this commit vs the baseline)")
        for bucket in ("changed", "new", "deleted", "unchanged"):
            by_kind = cls.get(bucket) or {}
            total = sum(by_kind.values())
            detail = ", ".join(f"{v} {k}" for k, v in sorted(by_kind.items())) or "-"
            L.append(f"    {bucket:<10}: {total:<4} ({detail})")

    L.append(_THIN)
    L.append("  REUSE ACCOUNTING (regenerated by the LLM  vs  reused/carried)")
    fn = stats.get("functions") or {}
    gl = stats.get("globals") or {}
    # Flowcharts reuse per-FUNCTION (M3.6). Fall back to the old file-based "files"
    # block for reports produced before the split existed.
    fc = stats.get("flowcharts") or stats.get("files") or {}
    sm = stats.get("files") or {}   # file-level summaries
    L.append(f"    Functions : regenerated {fn.get('regenerated', 0):<4} / {fn.get('total', 0):<4} "
             f"-> reused {fn.get('reused', 0)} ({_pct(fn.get('reused', 0), fn.get('total', 0))})")
    L.append(f"    Globals   : regenerated {gl.get('regenerated', 0):<4} / {gl.get('total', 0):<4} "
             f"-> reused {gl.get('reused', 0)} ({_pct(gl.get('reused', 0), gl.get('total', 0))})")
    L.append(f"    Flowcharts: regenerated {fc.get('regenerated', 0):<4} / {fc.get('total', 0):<4} function(s) "
             f"-> carried {fc.get('carried', 0)} ({_pct(fc.get('carried', 0), fc.get('total', 0))})")
    if decision == "incremental":
        L.append(f"    Summaries : {sm.get('regenerated', 0)} impacted file(s) re-summarized; the rest reused")

    L.append(_THIN)
    docs = stats.get("documents") or []
    L.append(_line("Documents", ", ".join(docs) if docs else "(none)"))
    warns = stats.get("warnings") or []
    if warns:
        L.append("  Warnings:")
        L.extend(f"    - {w}" for w in warns)
    L.append(_RULE)
    return L


def emit_report(lines: List[str], version_dir: str = None, logger_name: str = "incremental") -> None:
    """Log each line (-> logs/run_<date>.log + stderr) and persist to
    <version_dir>/report.txt."""
    try:
        from core.logging_setup import get_logger
        log = get_logger(logger_name)
        for ln in lines:
            log.info(ln)
    except Exception:
        for ln in lines:
            print(ln)
    if version_dir:
        try:
            with open(os.path.join(version_dir, "report.txt"), "w", encoding="utf-8") as fh:
                fh.write("\n".join(lines) + "\n")
        except OSError:
            pass
