"""
flowchart_engine.py — Main entry point.

Usage:
    python flowchart_engine.py \\
        --interface-json functions.json \\
        --metaData-json  metadata.json  \\
        --std            c++14          \\
        --clang-arg="-I/path/to/includes" \\
        --out-dir        output         \\
        --llm-url        http://localhost:11434/api/generate \\
        --llm-model      qwen2.5-coder:14b \\
        [--function-key  "src|file|qualified|params"]  \\
        [--no-cache]

The engine:
  1. Builds / restores the Project Knowledge Base (PKB) from functions.json
  2. Groups functions by source file
  3. For each source file, for each function:
       a. Extracts source text (by line range)
       b. Parses a libclang TranslationUnit (full, with bodies)
       c. Resolves the function cursor
       d. Builds the Control Flow Graph (CFG) via AST traversal
       e. Enriches CFG nodes with PKB context
       f. Calls LLM (one call per function) to generate labels
       g. Builds and validates the Mermaid script
  4. Writes one JSON file per source file to --out-dir
  5. Writes a _summary.json
"""

import argparse
import json
import logging
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

# When launched as a script, sys.path[0] is this file's directory (src/flowchart).
# Add the analyzer's src/ directory too so we can import the shared llm_core
# package (the single LlmClient used by the whole project).
_SRC_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _SRC_DIR not in sys.path:
    sys.path.insert(1, _SRC_DIR)

from ast_engine.cfg_builder import CFGBuilder
from ast_engine.parser import SourceExtractor, TranslationUnitParser
from ast_engine.resolver import find_function_cursor, get_function_body
from config import EngineConfig
from enrichment.enricher import NodeEnricher
from llm_core.client import LlmClient
from llm.generator import LabelGenerator
from mermaid.builder import build_mermaid
from mermaid.validator import validate_cfg, validate_mermaid
from models import FileResult, FlowchartResult, FunctionEntry, ProjectMeta
from output.writer import OutputWriter
from pkb.builder import ProjectKnowledgeBase
from pkb.cache import PkbCache
from pkb.knowledge import ProjectKnowledge, load_knowledge

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("flowchart_engine")


# ---------------------------------------------------------------------------
# Header-file detection and stub generation
# ---------------------------------------------------------------------------

# All recognised C/C++ header extensions (both cases for case-sensitive FSes).
_HEADER_SUFFIXES = frozenset({
    '.h', '.hpp', '.hxx', '.hh',
    '.H', '.HPP', '.HXX', '.HH',
})


def _is_header_file(path: str) -> bool:
    """Return True if path is a C/C++ header file based on its extension."""
    return Path(path).suffix in _HEADER_SUFFIXES




# ---------------------------------------------------------------------------
# CLI argument parsing
# ---------------------------------------------------------------------------

def _parse_args() -> EngineConfig:
    p = argparse.ArgumentParser(
        description="C++ → Mermaid flowchart generator powered by libclang + LLM",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        fromfile_prefix_chars='@',
    )

    p.add_argument("--interface-json", required=True,
                   help="Path to functions.json (generated by analyzer)")
    p.add_argument("--metaData-json", required=True,
                   help="Path to metadata.json (basePath, projectName)")
    p.add_argument("--std", default="c++14",
                   help="C++ standard for libclang (default: c++14)")
    p.add_argument("--clang-arg", dest="clang_args", action="append",
                   default=[], metavar="ARG",
                   help="Extra clang argument (repeatable, e.g. -I/path)")
    p.add_argument("--out-dir", required=True,
                   help="Output directory for JSON files")
    p.add_argument("--llm-url", default="http://localhost:11434/api/generate",
                   help="Local LLM endpoint URL")
    p.add_argument("--llm-model", default="qwen2.5-coder:14b",
                   help="LLM model name (default: qwen2.5-coder:14b)")
    p.add_argument("--function-key", default=None,
                   help="Process only this function key (optional filter)")
    p.add_argument("--knowledge-json", default=None,
                   dest="knowledge_json",
                   help="Path to project_knowledge.json built by project_scanner.py")
    p.add_argument("--no-cache", action="store_true",
                   help="Rebuild PKB from scratch (ignore disk cache)")
    p.add_argument("--cache-dir", default=".flowchart_cache",
                   help="Directory for PKB cache files (default: .flowchart_cache)")
    p.add_argument("--llm-timeout", type=int, default=120,
                   help="LLM request timeout in seconds (default: 120)")
    p.add_argument("--llm-retries", type=int, default=2,
                   help="LLM retry attempts on validation failure (default: 2)")
    p.add_argument("--llm-batch-size", type=int, default=4,
                   help="Nodes per LLM call (default: 4). Generator auto-halves on no-response.")
    p.add_argument("--llm-num-ctx", type=int, default=8192,
                   help="Ollama num_ctx (context window tokens, default: 8192). "
                        "Ollama defaults to 2048 which causes empty responses for "
                        "prompts >2048 tokens. Set higher for large functions.")
    p.add_argument("--max-stmts", type=int, default=3,
                   help="Max statements per ACTION node segment (default: 3)")
    p.add_argument("--max-lines", type=int, default=10,
                   help="Max source lines per ACTION node segment (default: 10)")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Enable debug logging")
    p.add_argument("--quiet", "-q", action="store_true",
                   help="Suppress info logging (warnings/errors only)")

    args = p.parse_args()

    # Configure unified logging (stderr + daily file). Idempotent.
    try:
        from core.logging_setup import configure_logging
        configure_logging(quiet=args.quiet, verbose=args.verbose)
    except Exception:
        if args.verbose:
            logging.getLogger().setLevel(logging.DEBUG)

    return EngineConfig(
        functions_json_path=args.interface_json,
        metadata_json_path=args.metaData_json,
        out_dir=args.out_dir,
        std=args.std,
        clang_args=args.clang_args,
        llm_url=args.llm_url,
        llm_model=args.llm_model,
        function_key=args.function_key,
        knowledge_json_path=args.knowledge_json,
        use_cache=not args.no_cache,
        cache_dir=args.cache_dir,
        llm_timeout=args.llm_timeout,
        llm_max_retries=args.llm_retries,
        max_stmts_per_segment=args.max_stmts,
        max_lines_per_segment=args.max_lines,
        llm_batch_size=args.llm_batch_size,
        llm_num_ctx=args.llm_num_ctx,
    )


# ---------------------------------------------------------------------------
# I/O loaders
# ---------------------------------------------------------------------------

def _load_json(path: str, label: str) -> Dict:
    p = Path(path)
    if not p.exists():
        logger.error("%s not found: %s", label, path)
        sys.exit(1)
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_project_meta(metadata_path: str) -> ProjectMeta:
    data = _load_json(metadata_path, "metadata.json")
    return ProjectMeta(
        base_path=data.get("basePath", "."),
        project_name=data.get("projectName", "unknown"),
    )


def _load_functions(functions_path: str) -> Dict:
    return _load_json(functions_path, "functions.json")


# ---------------------------------------------------------------------------
# PKB construction (with optional disk cache)
# ---------------------------------------------------------------------------

def _build_pkb(functions_data: Dict, config: EngineConfig) -> ProjectKnowledgeBase:
    pkb = ProjectKnowledgeBase()

    if config.use_cache:
        functions_json_str = json.dumps(functions_data, sort_keys=True)
        cache = PkbCache(config.cache_dir)
        cache.invalidate_stale(functions_json_str)
        cached = cache.load(functions_json_str)
        if cached:
            pkb.from_dict(cached)
            return pkb

    pkb.build(functions_data)

    if config.use_cache:
        functions_json_str = json.dumps(functions_data, sort_keys=True)
        cache = PkbCache(config.cache_dir)
        cache.save(functions_json_str, pkb.to_dict())

    return pkb


# ---------------------------------------------------------------------------
# Core per-function processing
# ---------------------------------------------------------------------------

def _process_function(
    func_entry: FunctionEntry,
    pkb: ProjectKnowledgeBase,
    source_extractor: SourceExtractor,
    tu_parser: TranslationUnitParser,
    label_generator: LabelGenerator,
    config: EngineConfig,
    base_path: str,
    project_knowledge: Optional[ProjectKnowledge] = None,
) -> FlowchartResult:
    """
    Process a single function end-to-end.
    Returns a FlowchartResult (with error field set on failure).
    """
    key = func_entry.key
    qn = func_entry.qualified_name

    try:
        # 1. Extract source text by line range
        source_code = source_extractor.extract_by_lines(
            func_entry.file, func_entry.line, func_entry.end_line
        )
        source_lines = source_extractor.get_lines(func_entry.file)

        # 2. Parse full TU (with function bodies)
        abs_path = source_extractor.abs_path(func_entry.file)
        tu = tu_parser.get_tu_full(abs_path)

        # 3. Resolve function cursor
        # Pass abs_path so the resolver can use Strategy 1 (direct position
        # lookup) and can match loc.file.name against the exact parsed path.
        func_cursor = find_function_cursor(tu, func_entry, abs_path)
        if func_cursor is None:
            raise RuntimeError(
                f"Could not resolve cursor for '{qn}' in {func_entry.file}:{func_entry.line}"
            )

        # 4. Build CFG
        builder = CFGBuilder(
            source_lines,
            max_stmts=config.max_stmts_per_segment,
            max_lines=config.max_lines_per_segment,
        )
        cfg = builder.build(func_cursor, func_entry)
        logger.debug("CFG built: %d nodes, %d edges for '%s'",
                     len(cfg.nodes), len(cfg.edges), qn)

        # 5. Enrich CFG nodes with PKB context + project knowledge
        enricher = NodeEnricher(
            pkb,
            source_lines_by_file={func_entry.file: source_lines},
            knowledge=project_knowledge,
        )
        enricher.enrich(cfg, func_entry)

        # 6. Generate LLM labels (one call per function)
        label_generator.label_cfg(cfg, func_entry, source_code, base_path)

        # 7. Validate CFG
        cfg_validation = validate_cfg(cfg)
        if not cfg_validation.is_valid:
            logger.warning("CFG validation errors for '%s':\n%s", qn, cfg_validation)
        elif cfg_validation.warnings:
            logger.debug("CFG validation warnings for '%s':\n%s", qn, cfg_validation)

        # 8. Build Mermaid script
        mermaid_script = build_mermaid(cfg)

        # 9. Validate Mermaid script
        mermaid_validation = validate_mermaid(mermaid_script)
        if not mermaid_validation.is_valid:
            logger.warning("Mermaid validation errors for '%s':\n%s",
                           qn, mermaid_validation)

        return FlowchartResult(
            function_key=key,
            qualified_name=qn,
            mermaid_script=mermaid_script,
        )

    except Exception as exc:
        logger.error("Failed to process '%s': %s", qn, exc, exc_info=True)
        return FlowchartResult(
            function_key=key,
            qualified_name=qn,
            mermaid_script="",
            error=str(exc),
        )


# ---------------------------------------------------------------------------
# LLM client construction
# ---------------------------------------------------------------------------

def _load_analyzer_llm_config() -> Optional[Dict]:
    """Return the resolved llm config block, walking up from cwd.

    flowchart_engine is launched with cwd=project_root by views/flowcharts.py,
    so the first hit is the analyzer config. Returns None if no config.json
    is reachable (e.g. standalone CLI invocation from another directory).

    Raises LlmConfigError (from core.config) if the config.json IS reachable
    but has missing/invalid required fields — that is a user-facing error,
    not a silent fallback.
    """
    from utils import load_config, load_llm_config  # noqa: WPS433
    cwd = os.path.abspath(os.getcwd())
    for candidate in (cwd, os.path.dirname(cwd)):
        cfg_path = os.path.join(candidate, "config", "config.json")
        if os.path.isfile(cfg_path):
            cfg = load_config(candidate)
            return load_llm_config(cfg)
    return None


def _build_llm_client(config: EngineConfig, llm_cfg: Optional[Dict]):
    """Build an LlmClient from the resolved llm config, or legacy CLI args.

    When *llm_cfg* is provided (analyzer config was reachable), we use the
    unified from_config path so provider/custom headers/retries/api_key all
    flow through. Otherwise fall back to the legacy CLI-arg constructor
    (Ollama only, backwards compatible with standalone subprocess usage).
    """
    if llm_cfg is not None:
        from llm_core.client import from_config  # noqa: WPS433
        # CLI args still win for num_ctx if explicitly larger — lets a
        # standalone caller bump the window without editing config.json.
        if config.llm_num_ctx and config.llm_num_ctx > llm_cfg["numCtx"]:
            llm_cfg["numCtx"] = config.llm_num_ctx
        return from_config(llm_cfg)

    # Legacy fallback — works for standalone Ollama-only invocations.
    return LlmClient(
        url=config.llm_url,
        model=config.llm_model,
        timeout=config.llm_timeout,
        temperature=config.llm_temperature,
        num_ctx=config.llm_num_ctx,
    )


# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------

def run(config: EngineConfig) -> None:
    logger.info("=" * 60)
    logger.info("flowchart_engine starting")
    logger.info("  functions.json : %s", config.functions_json_path)
    logger.info("  metadata.json  : %s", config.metadata_json_path)
    logger.info("  out-dir        : %s", config.out_dir)
    if config.knowledge_json_path:
        logger.info("  knowledge-json : %s", config.knowledge_json_path)
    if config.function_key:
        logger.info("  filter key     : %s", config.function_key)
    logger.info("=" * 60)

    # Resolve and display the LLM config the subprocess is actually going to
    # use. Any missing/invalid required field surfaces here as LlmConfigError,
    # so the user sees the exact failing field instead of a silent fallback.
    from utils import format_llm_config_banner, LlmConfigError  # noqa: WPS433
    try:
        llm_cfg_resolved = _load_analyzer_llm_config()
    except LlmConfigError as exc:
        logger.error("Invalid LLM config: %s", exc)
        sys.exit(2)
    if llm_cfg_resolved is not None:
        for _line in format_llm_config_banner(llm_cfg_resolved).splitlines():
            logger.info(_line)
    else:
        logger.info("LLM (legacy standalone): %s  model=%s",
                    config.llm_url, config.llm_model)

    # Load inputs
    meta = _load_project_meta(config.metadata_json_path)
    functions_data = _load_functions(config.functions_json_path)
    base_path = meta.base_path

    logger.info("Project: %s  |  base_path: %s", meta.project_name, base_path)
    logger.info("Loaded %d functions from functions.json", len(functions_data))

    # Load project knowledge (optional — built by project_scanner.py)
    project_knowledge: Optional[ProjectKnowledge] = None
    if config.knowledge_json_path:
        project_knowledge = load_knowledge(config.knowledge_json_path)
        if project_knowledge is None:
            logger.warning("--knowledge-json file not loaded; continuing without it")
    else:
        logger.info("No --knowledge-json provided; running without project knowledge")

    # Build PKB
    pkb = _build_pkb(functions_data, config)

    # Attach project knowledge to PKB for richer context packets
    if project_knowledge:
        pkb.load_project_knowledge(project_knowledge)

    # Apply function-key filter
    if config.function_key:
        if config.function_key not in functions_data:
            logger.error("function-key not found in functions.json: %s",
                         config.function_key)
            sys.exit(1)
        target_keys = [config.function_key]
        logger.info("Filtered to 1 function: %s", config.function_key)
    else:
        target_keys = list(functions_data.keys())

    # Build FunctionEntry objects for targets
    target_entries: List[FunctionEntry] = []
    for key in target_keys:
        entry = pkb.get(key)
        if entry:
            target_entries.append(entry)
        else:
            logger.warning("Key not in PKB (skipping): %s", key)

    # Drop functions defined in header files — they cannot be parsed as
    # standalone TUs and their bodies are not worth analysing.  They already
    # appear as ACTION nodes in their callers' flowcharts.
    non_header = [e for e in target_entries if not _is_header_file(e.file)]
    skipped_headers = len(target_entries) - len(non_header)
    if skipped_headers:
        logger.info("Skipping %d header-defined function(s) (no output generated)",
                    skipped_headers)

    # Group by source file (deterministic order)
    by_file: Dict[str, List[FunctionEntry]] = defaultdict(list)
    for entry in non_header:
        by_file[entry.file].append(entry)

    logger.info("Processing %d function(s) across %d source file(s)",
                len(target_entries), len(by_file))

    # Initialise shared infrastructure
    source_extractor = SourceExtractor(base_path)
    tu_parser = TranslationUnitParser(config.std, config.clang_args)
    llm_client = _build_llm_client(config, llm_cfg_resolved)

    # Derive enrichment flags + authoritative max_context_tokens from the
    # resolved llm config (displayed above). When standalone without a
    # reachable config, both stay None and every enrichment feature is off.
    enrichment_cfg: Dict = {}
    max_context_tokens: Optional[int] = None
    if llm_cfg_resolved is not None:
        from llm_core.budget import resolve_max_tokens  # noqa: WPS433
        enrichment_cfg = llm_cfg_resolved.get("enrichment") or {}
        max_context_tokens = resolve_max_tokens(llm_cfg_resolved)
        logger.info("Coherence/simplify budget = %d tokens (provider=%s)",
                    max_context_tokens, llm_cfg_resolved.get("provider"))

    label_generator = LabelGenerator(
        client=llm_client,
        pkb=pkb,
        max_retries=config.llm_max_retries,
        batch_size=config.llm_batch_size,
        enrichment_config=enrichment_cfg,
        max_context_tokens=max_context_tokens,
    )
    writer = OutputWriter(config.out_dir)

    # Process each source file
    file_results: List[FileResult] = []
    total_ok = 0
    total_err = 0

    for source_file, entries in sorted(by_file.items()):
        logger.info("── File: %s  (%d function(s))", source_file, len(entries))
        fr = FileResult(source_file=source_file)

        for entry in entries:
            logger.info("   Processing: %s", entry.qualified_name)
            result = _process_function(
                func_entry=entry,
                pkb=pkb,
                source_extractor=source_extractor,
                tu_parser=tu_parser,
                label_generator=label_generator,
                config=config,
                base_path=base_path,
                project_knowledge=project_knowledge,
            )
            fr.flowcharts.append(result)
            if result.error:
                total_err += 1
                logger.warning("   ✗ Error: %s", result.error)
            else:
                total_ok += 1
                logger.info("   ✓ OK: %d chars of Mermaid",
                            len(result.mermaid_script))

        file_results.append(fr)

    # Write output
    written = writer.write_all(file_results)
    writer.write_summary(file_results, total_ok + total_err, total_err)

    logger.info("=" * 60)
    logger.info("Done.  ✓ %d  ✗ %d  |  %d file(s) written",
                total_ok, total_err, len(written))
    logger.info("Output: %s", config.out_dir)
    logger.info("=" * 60)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    config = _parse_args()
    run(config)
