"""Why does this function's source_hash never change, even under a FULL parse?

`hash_cursor` (incremental/hashing.py) token-hashes a libclang cursor. On any exception
it falls back to an EMPTY token list, and `hash_tokens([])` is sha256("") -- a constant.
So a function whose tokens libclang cannot produce gets the same hash on every run, in
every version, forever. It is classified UNCHANGED, its flowchart and description are
carried forward, and nothing is logged. The same is true, less severely, of any two
functions that collide on a hash.

That is invisible to the usual checks: the hash is present and well-formed, it just
never moves. This reports it directly, then asks git whether the edit is even in the
range being compared -- the other way a hash legitimately stays put.

    python tools/why_unchanged.py --project-id P --baseline v1 --target v4 --name myFunc
    python tools/why_unchanged.py --project-id P --baseline v1 --target v4   (survey only)
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import os
import subprocess
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path[:0] = [_ROOT, os.path.join(_ROOT, "engine")]

# hash_tokens([]) with no doc comment: the hash every token-less entity collapses onto.
EMPTY_HASH = hashlib.sha256(b"").hexdigest()
_TAB = chr(9)


def _git(repo, *args):
    r = subprocess.run(["git", "-C", repo] + list(args), capture_output=True, text=True,
                       shell=(os.name == "nt"))
    return r.stdout if r.returncode == 0 else ""


def _real_path(repo, path):
    """The path as git actually spells it. The parser records paths with whatever casing
    libclang reports, which on Windows need not match the index -- and `git show` is
    case-sensitive even when the filesystem is not."""
    want = (path or "").replace("\\", "/").strip("/").lower()
    for ln in _git(repo, "ls-files").splitlines():
        if ln.strip().lower() == want:
            return ln.strip()
    return None


def _checkout_dir(pid, *shas):
    wroot = os.path.join(_ROOT, "workspaces", pid)
    for sha in shas:
        if sha and os.path.isdir(os.path.join(wroot, sha[:16], ".git")):
            return os.path.join(wroot, sha[:16])
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-id", required=True)
    ap.add_argument("--baseline", required=True)
    ap.add_argument("--target", required=True)
    ap.add_argument("--name", help="the function to trace (substring of its key)")
    ap.add_argument("--repo", help="the C++ checkout, if not under workspaces/<project-id>")
    ap.add_argument("--limit", type=int, default=15)
    a = ap.parse_args()

    import sqlalchemy as sa
    from core.db import get_engine
    eng = get_engine()

    def rows(vid):
        q = ("select e.entity_key, v.source_hash, v.file, v.line, v.end_line "
             "from entity_versions v join entities e on e.entity_id = v.entity_id "
             "where v.version_id = :v and e.kind = 'function'")
        with eng.connect() as cx:
            return {r[0]: (r[1], r[2], r[3], r[4]) for r in cx.execute(sa.text(q), {"v": vid})}

    def sha_of(vid):
        with eng.connect() as cx:
            r = cx.execute(sa.text("select commit_sha from versions where id = :v"),
                           {"v": vid}).fetchone()
        return r[0] if r else None

    rb, rt = rows(a.baseline), rows(a.target)
    if not rt:
        print("no functions stored for %s -- check the version id." % a.target)
        return 2

    # ---- 1. is change detection even capable of moving? ------------------------------
    print("=" * 78)
    print("HASH HEALTH  in %s" % a.target)
    print("=" * 78)
    empty = sorted(k for k, v in rt.items() if v[0] == EMPTY_HASH)
    blank = sorted(k for k, v in rt.items() if not v[0])
    print("  %d function(s) total" % len(rt))
    print("  %d have the EMPTY-TOKEN hash (sha256 of nothing)" % len(empty))
    print("  %d have no hash stored at all" % len(blank))
    if empty:
        print()
        print("  *** These functions produced NO libclang tokens. Their hash is a constant,")
        print("      so they are UNCHANGED in every comparison, forever -- their flowcharts")
        print("      and descriptions can never be regenerated by a code edit.")
        for k in empty[:a.limit]:
            print("      %s   [%s]" % (k, rt[k][1] or "?"))

    dup = collections.Counter(v[0] for v in rt.values() if v[0])
    clusters = [(h, n) for h, n in dup.items() if n > 1 and h != EMPTY_HASH]
    clusters.sort(key=lambda x: -x[1])
    if clusters:
        print()
        print("  %d hash value(s) are shared by more than one function; largest:"
              % len(clusters))
        for h, n in clusters[:5]:
            names = [k for k, v in rt.items() if v[0] == h][:3]
            print("      %d functions share %s  e.g. %s" % (n, h[:12], ", ".join(names)))
        print("      (identical bodies hash identically -- expected for trivial stubs,")
        print("       suspicious for large ones.)")

    if not a.name:
        return 0

    # ---- 2. the named function -------------------------------------------------------
    hits = [k for k in rt if a.name.lower() in k.lower()]
    print()
    print("=" * 78)
    print("TRACE  %s" % a.name)
    print("=" * 78)
    if not hits:
        print("  no function matching that name in %s." % a.target)
        return 2

    sha_b, sha_t = sha_of(a.baseline), sha_of(a.target)
    repo = a.repo or _checkout_dir(a.project_id, sha_t, sha_b)
    have_git = bool(repo and os.path.isdir(os.path.join(repo, ".git")))

    for k in hits[:5]:
        ht, ft, lt, et = rt[k]
        hb, fb, lb, eb = rb.get(k, (None, None, None, None))
        print()
        print("  %s" % k)
        print("      file          : %s" % (ft or "?"))
        print("      lines         : %s..%s in %s" % (lb, eb, a.baseline))
        print("                      %s..%s in %s" % (lt, et, a.target))
        print("      hash %-10s: %s" % (a.baseline, (hb or "-")[:24]))
        print("      hash %-10s: %s" % (a.target, (ht or "-")[:24]))
        if ht and ht == EMPTY_HASH:
            print("      *** EMPTY-TOKEN HASH -- libclang produced no tokens for this")
            print("          function. Change detection cannot work for it at all.")
        elif hb and ht and hb == ht:
            print("      the hash did NOT move between these two versions.")

        if not have_git:
            print("      (no checkout found; pass --repo to check the source itself)")
            continue

        real = _real_path(repo, ft or "")
        if not real:
            print("      *** git does not track a file spelled %r." % (ft or ""))
            print("          The parser recorded a path git cannot resolve.")
            continue
        if real != (ft or "").replace("\\", "/").strip("/"):
            print("      note: git spells this path %r" % real)
            print("            the model spells it   %r  (casing differs)" % ft)

        if not (sha_b and sha_t):
            continue
        # Did the commit range touch this file at all, and these lines in particular?
        touched = _git(repo, "diff", "--name-only", "%s..%s" % (sha_b, sha_t), "--", real).strip()
        print("      file changed between the commits : %s" % ("yes" if touched else "NO"))
        if not touched:
            print("          -> the hash is RIGHT to stay put. The edit you are looking for")
            print("             is not in this commit range.")
            continue
        hunks = []
        for ln in _git(repo, "diff", "-U0", "%s..%s" % (sha_b, sha_t), "--", real).splitlines():
            if ln.startswith("@@"):
                try:
                    seg = ln.split("+", 1)[1].split(" ", 1)[0]
                    start = int(seg.split(",")[0])
                    count = int(seg.split(",")[1]) if "," in seg else 1
                    hunks.append((start, start + max(count - 1, 0)))
                except Exception:
                    pass
        if lt and et:
            inside = [h for h in hunks if not (h[1] < lt or h[0] > et)]
            print("      %d changed hunk(s) in the file; %d inside lines %s..%s"
                  % (len(hunks), len(inside), lt, et))
            if hunks and not inside:
                print("          -> the file changed but NOT this function's lines. The hash")
                print("             is right; look at what else the document shows for it.")
            elif inside:
                print("          -> this function's own lines changed, so its hash MUST move.")
                print("             It did not: change detection is broken for it.")
                for s, e in inside[:5]:
                    print("             changed lines %s..%s" % (s, e))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
