"""End-of-run generation report (M3.4).

A human-readable summary of what a generation did — inputs (baseline/scope/commit),
change classification, and reuse accounting (regenerated vs reused per entity kind)
— so it's easy to see how incremental reuse is performing. `build_report` is pure
(takes a stats dict) so it's unit-testable; `emit_report` logs it + saves report.txt.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List

_W = 64
_RULE = "=" * _W
_THIN = "-" * _W


def _pct(part: int, whole: int) -> str:
    return f"{(100 * part // whole) if whole else 0}%"


def _line(label: str, value: Any) -> str:
    return f"  {label:<16}: {value}"


def _llm_lines(counts: Dict[str, Any]) -> List[str]:
    """The LLM section: how many calls a run made, and how many produced nothing.

    Token counts already say what was SPENT. They do not say whether the spending bought
    anything, and that gap hid a real failure: a run took 2062 seconds and produced mechanical
    flowchart labels while the gateway answered every request correctly — the replies were being
    destroyed after arrival. Tokens looked healthy throughout. "1 call in 3 returned nothing" is
    the line that would have pointed straight at it.

    `counts` is {(kind, outcome): n} flattened to {"kind|outcome": n} by the caller, summed
    across every phase subprocess.
    """
    if not counts:
        return []
    if "__unavailable__" in counts:
        return [_THIN,
                "  LLM CALLS : accounting unavailable "
                f"({counts['__unavailable__']})",
                "              Run `python tools/db_setup.py` to apply migration 0007. Until "
                "then the",
                "              report cannot say how many LLM calls failed."]
    by_kind: Dict[str, Dict[str, int]] = {}
    for key, n in counts.items():
        kind, _, outcome = str(key).partition("|")
        by_kind.setdefault(kind, {}).setdefault(outcome, 0)
        by_kind[kind][outcome] += int(n or 0)

    tot = {"ok": 0, "empty": 0, "error": 0}
    for oc in by_kind.values():
        for k in tot:
            tot[k] += oc.get(k, 0)
    calls = sum(tot.values())
    if not calls:
        return []

    failed = tot["empty"] + tot["error"]
    L = [_THIN, "  LLM CALLS (a failed call means the caller fell back to a mechanical result)"]
    L.append(f"    Total     : {calls:<5}  answered {tot['ok']} ({_pct(tot['ok'], calls)})")
    if failed:
        L.append(f"    Failed    : {failed:<5}  empty {tot['empty']}, error {tot['error']}"
                 f"  -> {_pct(failed, calls)} of calls produced NOTHING")
    for kind in sorted(by_kind):
        oc = by_kind[kind]
        k_ok, k_empty, k_err = oc.get("ok", 0), oc.get("empty", 0), oc.get("error", 0)
        k_tot = k_ok + k_empty + k_err
        detail = f"ok {k_ok}"
        if k_empty:
            detail += f", empty {k_empty}"
        if k_err:
            detail += f", error {k_err}"
        L.append(f"      {kind:<22} {k_tot:<5}  ({detail})")
    if failed:
        L.append("    A non-zero failed count means the document contains fallback text or")
        L.append("    mechanical labels. Check the log for 'empty response' / 'HTTP'.")
    return L


def build_report(stats: Dict[str, Any]) -> List[str]:
    """Build the report lines from a stats dict (see generate_incremental/full)."""
    decision = stats.get("decision", "full")
    L: List[str] = [_RULE, f"  GENERATION REPORT  -  version {stats.get('versionId')}  ({decision})", _RULE]

    L.append(_line("Project", stats.get("projectId")))
    L.append(_line("Branch / commit", f"{stats.get('branch')} / {str(stats.get('commit'))[:10]}"))
    L.append(_line("Scope", stats.get("scope")))
    if decision == "incremental":
        L.append(_line("Baseline", f"{stats.get('baselineVersionId')} @ "
                                   f"{str(stats.get('baselineCommit'))[:10]}  "
                                   f"({stats.get('changedFiles')} changed file(s) in the diff)"))
    else:
        L.append(_line("Baseline", "(none - full generation; becomes the baseline for future runs)"))
    L.append(_line("Data dict", stats.get("dataDictId")))
    L.append(_line("LLM model", stats.get("llmModel")))
    L.append(_line("Status", stats.get("status")))
    if stats.get("elapsedSeconds") is not None:
        L.append(_line("Wall clock", f"{stats['elapsedSeconds']:.1f}s"))

    if decision == "incremental":
        cls = stats.get("classification") or {}
        L.append(_THIN)
        L.append("  CHANGE CLASSIFICATION (this commit vs the baseline)")
        for bucket in ("changed", "new", "deleted", "unchanged"):
            by_kind = cls.get(bucket) or {}
            total = sum(by_kind.values())
            detail = ", ".join(f"{v} {k}" for k, v in sorted(by_kind.items())) or "-"
            L.append(f"    {bucket:<10}: {total:<4} ({detail})")

    L.append(_THIN)
    L.append("  REUSE ACCOUNTING (regenerated by the LLM  vs  reused/carried)")
    fn = stats.get("functions") or {}
    gl = stats.get("globals") or {}
    # Flowcharts reuse per-FUNCTION (M3.6). Fall back to the old file-based "files"
    # block for reports produced before the split existed.
    fc = stats.get("flowcharts") or stats.get("files") or {}
    sm = stats.get("files") or {}   # file-level summaries
    L.append(f"    Functions : regenerated {fn.get('regenerated', 0):<4} / {fn.get('total', 0):<4} "
             f"-> reused {fn.get('reused', 0)} ({_pct(fn.get('reused', 0), fn.get('total', 0))})")
    L.append(f"    Globals   : regenerated {gl.get('regenerated', 0):<4} / {gl.get('total', 0):<4} "
             f"-> reused {gl.get('reused', 0)} ({_pct(gl.get('reused', 0), gl.get('total', 0))})")
    # Globals reuse legitimately runs much lower than functions, and a bare 0% reads like a
    # broken feature. A global's LLM description embeds the DESCRIPTIONS of the functions that
    # read and write it, so regenerating any of those genuinely changes the global's input —
    # it must be regenerated too. With few globals and each touched by only one or two
    # functions, a small change can invalidate all of them. Say so rather than leave the
    # number to be misread.
    #
    # This note used to describe an intention the code did not implement: a global's fingerprint
    # was its own source hash with NO dependencies, so a changed reader left it untouched and the
    # reuse index handed back a description written against the reader's old behaviour. Globals
    # now fold their accessors' hashes in, which is what makes the sentence below true.
    if gl.get("total") and not gl.get("reused"):
        L.append("                (0% is expected here: a global's description embeds its "
                 "readers'/writers' descriptions,")
        L.append("                 so every global touched by a regenerated function is "
                 "regenerated too)")
    L.append(f"    Flowcharts: regenerated {fc.get('regenerated', 0):<4} / {fc.get('total', 0):<4} function(s) "
             f"-> carried {fc.get('carried', 0)} ({_pct(fc.get('carried', 0), fc.get('total', 0))})")
    if decision == "incremental":
        L.append(f"    Summaries : {sm.get('regenerated', 0)} impacted file(s) re-summarized; the rest reused")
        # M3.7 — entities reused from the cross-version index (reverts / cross-branch),
        # i.e. copied from a non-baseline version instead of regenerated.
        xv = stats.get("crossVersion") or {}
        xv_fn, xv_gl, xv_fc = xv.get("functions", 0), xv.get("globals", 0), xv.get("flowcharts", 0)
        if xv_fn or xv_gl or xv_fc:
            L.append(f"    X-version : {xv_fn} function(s) + {xv_gl} global(s) + {xv_fc} flowchart(s) reused "
                     f"from a prior version via the content index (revert / cross-branch)")

    L.extend(_llm_lines(stats.get("llmCalls") or {}))

    L.append(_THIN)
    docs = stats.get("documents") or []
    L.append(_line("Documents", ", ".join(docs) if docs else "(none)"))
    warns = stats.get("warnings") or []
    if warns:
        L.append("  Warnings:")
        L.extend(f"    - {w}" for w in warns)
    L.append(_RULE)
    return L


def emit_report(lines: List[str], version_dir: str = None, logger_name: str = "incremental",
                *, write_file: bool = True) -> None:
    """Log each line (-> logs/run_<date>.log + stderr) and, when asked, write report.txt.

    `write_file=False` in database mode: the report is stored verbatim in `versions.report`,
    and nothing reads the file — it was write-only. Every line still goes to the log, so the
    run is no less inspectable on the machine that produced it, and now it is inspectable from
    any other node too.
    """
    try:
        from core.logging_setup import get_logger
        log = get_logger(logger_name)
        for ln in lines:
            log.info(ln)
    except Exception:
        for ln in lines:
            print(ln)
    if version_dir and write_file:
        try:
            with open(os.path.join(version_dir, "report.txt"), "w", encoding="utf-8") as fh:
                fh.write("\n".join(lines) + "\n")
        except OSError:
            pass
